// Note: Changed id to number (instead of string in the spec) so that it can be easily auto-incremented.

export type TODO = {
  id: number // Autogenerated.
  message: string
  label: string // Label ID
  dueDate: Date // Datetime in ISO-8601
}
